### ISSUE TITLE
Taskbar icon

### ISSUE THREAD

**Issue by andytt11** [vexorian/dizquetv#120]
Moving the program to the taskbar would be awesome on windows.

**Comment by MoRBiD-MaNGLeR** [comment]
@andytt11 This is not likely to be worked on since dizqueTV is intended to be platform agnostic.

As a workaround:  If you use Chrome, open Chrome to your desired dizqueTV page.  (For me, I like to go to the Guide.)  Click and hold in the Chrome address bar on the address and drag it to the Chrome icon on your taskbar and let go.  Then, if you right-click the Chrome icon, you'll find that the dizqueTV URL is now pinned to your Chrome icon's right-click menu.  Left-click the URL to launch the page.  Let us know if you have any questions about this workaround.

**Comment by andytt11** [comment]
I meant as for the running channel program instead of being on the taskbar being moved as a task icon but thank your suggestion, apparently I couldn't string a sentence together last night.

**Comment by vexorian** [comment]
wontfix sounds about right.

dizqueTV is meant to run as a service. So neither the taskbar application or the status icon are proper ways to have it. But in windows it can be configured as a service. I really hope the wiki can be enhanced to include instructions for this, or at least a link to someone else's documentation of how to setup an .exe to run as a service. Now that I think of it, Linux possibly needs the same sort of wiki page. But I'll be closing this now.
