### ISSUE TITLE
Add a license to the repo

### ISSUE THREAD

**Issue by nwithan8** [vexorian/dizquetv#135]
After recent events in the Discord regarding forking this repo or the original PseudoTV repo, and just to be clear about future forks and/or contributions, I think you should add a license to this repo, either a GPLv3 or MIT.

**Comment by vexorian** [comment]
Oh boy. I actually assumed it had a license.


 Actually since the original pseudotv was published without a license I am not sure how it works about adding licenses to forks. I will have to read up a bit. If I remember correctly, this means all the original pseudotv-plex code is Public Domain and I can add a license to all the new code. But I am not entirely sure about it.
