### ISSUE TITLE
Time Slots: Can't delete all Time Slots from a channel

### ISSUE THREAD

**Issue by MoRBiD-MaNGLeR** [vexorian/dizquetv#169]
I can't delete all Time Slots from a channel using the Time Slots panel.  The Cancel button exits without saving, and the Create Lineup button is understandably grayed out.  Please add a way for users to do this via the Time Slots panel.

**Comment by vexorian** [comment]
Well the time slots are saved as a memory of the last time you clicked the apply. I don't understand why you want to delete them without applying?

**Comment by MoRBiD-MaNGLeR** [comment]
What do you mean without applying?  I'm revisiting a channel where I have Time Slots set up, and I want to remove the Time Slots.  I can remove all but one.

**Comment by MoRBiD-MaNGLeR** [comment]
Here I removed all but one:

![image](https://user-images.githubusercontent.com/34169521/96187113-4c99ff00-0ef1-11eb-895e-7a78e5f52527.png)


Here I'm trying to remove the last one.  Notice that the Create Lineup button is now understandably grayed out?  Cancel just aborts what you're trying to do.  Reopen Time Slots, and it's still there.  I can't remove the last Time Slot:

![image](https://user-images.githubusercontent.com/34169521/96187182-68050a00-0ef1-11eb-8d00-5b2a075a93fd.png)

**Comment by nwithan8** [comment]
How do you imagine this feature working?
If you remove all the time slots, what happens to the programs on the channel? Are they removed? Are they reordered (if so, in what order)?

**Comment by MoRBiD-MaNGLeR** [comment]
You add content to a channel before setting up Time Slots.  When removing all of the Time Slots, I would expect the content to remain.  The user could then go remove the content if desired.

I stopped setting up channels with Time Slots since there's not a way to remove the last Time Slot if the desire is to revert back to having no Time Slots.  But I would like to use them.

**Comment by nwithan8** [comment]
What order would the content be in once you remove the time slots?

**Comment by MoRBiD-MaNGLeR** [comment]
Would be?  I don't know.  I can't remove all the Time Slots.  (What's the order when removing one Time Slot of several.  That would likely be your answer.)

Should be?  Probably as the content was when the Time Slots existed.  At that point, the user could use the other Tools to do whatever is desired.

**Comment by vexorian** [comment]
Time slots are a tool. They are like the tweak weights or remove shows tools in the sense that they need a separate dialog.  When you click the apply button, you are not *adding* time slots  you are applying a transformation to the channel's programming based on the time slots you set up.

Just like you can't restore the original weights after using tweak weights or the original order after doing a shuffle. There isn't a feature to undo the application of time slots.  And if you accidentally do mess up with the time slots (or any other tool) you can click the cancel button and the modification won't be saved. And even if it gets saved. You can always just hit remove all, add the programs again and start over.

I think I can add an undo button for tools so that previous programming can be restored. This would only work *before* saving the channel, though. Because including the whole programming history would make the channel json bigger and that's the last thing we need.

**Comment by MoRBiD-MaNGLeR** [comment]
Let's stop focusing on the channel content and go back to my original concern of the Time Slots dialog.  I want to delete the last Time Slot listed on the Time Slots dialog and it won't me:

![image](https://user-images.githubusercontent.com/34169521/96825660-859d0c80-13e6-11eb-94d5-01ccab5b8ac4.png)

**Comment by vexorian** [comment]
But again, the Create Lineup button doesn't just add time slots to the programming. It applies a transformation. So if you delete all the time slots and hit "Create Lineup", then it would be the same as hitting remove all or maybe it would replace the whole programming with flex. Both alternatives seem quite pointless.

**Comment by nwithan8** [comment]
It's the same concept.

Every time you add or remove a time slot (and hit save), a new schedule is made using the time slots (the programs and times you indicated), and the channel's programming order is updated with this schedule.

If you were to remove all time slots, effectively making an empty schedule with no programs (since only the programs indicated in the time slots are used in the schedule/programming list -> no time slots, no programs), there would be no programs left on the channel.

You would have an empty channel, since there's no record of what programs were on the channel before you started adding and removing time slots.

**Comment by MoRBiD-MaNGLeR** [comment]
But you can't remove all of the Time Slots.  It won't let you delete all of them.

I'm okay with it creating an empty schedule at that point as long as the rest of the channel setup remains intact.

But regardless of that, the Time Slots on the Time Slots dialog should all be deleted at that point.  But I can't delete the last Time Slot.  Anything you add you should be able to remove.

**Comment by vexorian** [comment]
Well, okay. A thing about the time slots is that they save a json backup for the setting that was used. I added this for convenience because the schedule is really hard to setup and this allows you to reapply the schedule after adding a new episode.

It is true that it is not possible to remove it. But I thought that in that case someone could just add a single flex slot there.

How about a "Reset" button that empties the time slots settings and thus the backup will be gone?

**Comment by nwithan8** [comment]
I don't think Vex has a problem with adding the ability to delete the last time slot. We're just trying to figure out what you want to happen when you do that so he can design the feature.

It sounds like you (though I'm sure others will disagree with it, knowing these picky users) want deleting the last time slot to result in an empty channel.

If I recall correctly, currently you can't have an empty channel. There has to be at least one program (or flex, or offline time, or redirect) on the channel, correct @vexorian ? So maybe if the call to the time slots API endpoint returns a blank programming list, it injects a small offline flex time and that's the "blank" channel?

**Comment by MoRBiD-MaNGLeR** [comment]
Like you said, you'll likely get different opinions from the users on this.

I would expect it to leave the programming alone.  The Time Slots didn't add the programming.  I had to do that before setting up the Time Slots.  So removing the Time Slots should leave the programming behind.  If the Time Slots added the programming, then I could see it removing the programming as well.  It wouldn't be the end of the world if it removed the programming (and added a single Flex Time entry to avoid an empty channel), but it seems a little heavy handed since I added the programming.  If it does remove the programming, perhaps the button should change from "Create Lineup" to "Delete Lineup and Content"?

Since we're on the topic of revisiting Time Slots, ideally, I'd like to be able to schedule a single Program Block with Time Slots and have the option to repeat that Program Block for the rest of the day, rather than have to schedule each program all day.  For instance, if I have four 30-minute programs in a Program Block, I'd then like to be able to have that Program Block repeat 12 times that day.  I don't want the same episodes to play, but I want the same shows to play.  This would play the first show at Midnight, 2am, 4am, etc.; the second show at 12:30am, 2:30am, 4:30am, etc.; and so on.  For the 12 airings of each show that day, they would air different episodes, in order or shuffled depending on the setting chosen for the Time Slot.  Please consider if you're revisiting Time Slots.  Thanks, guys.

**Comment by nwithan8** [comment]
RE: Leaving programming alone.

Actually, Time Slots does alter the programming, since it replaces the program and order of the channels with the schedule you make. If you add 1000 items to your channel, but then make one time slot for one movie, the program list on your channel is going to be updated to only be that one movie. All the other programs will disappear.

So deleting the time slot won't restore the original programming list you had before making time slots.

Either it could make an "empty" channel, or we could store a backup of the original programming list before you start making time slots, so it could restore that if the time slots were deleted (that's a lot of overhead)

**Comment by MoRBiD-MaNGLeR** [comment]
I didn't realize it would delete the 1000 items.  When I used Time Slots, I scheduled all of the content that I had added.  That's good to know.

The cleaner approach would be to leave behind a single Flex Time entry, provided the last Time Slot can be deleted.  We don't want the overhead.

And if the repeating Program Block concept could be scoped for Time Slots, I'd appreciate it.

**Comment by vexorian** [comment]
There are a couple of things I want to do eventually I think there will be a separation between what programs are available and the schedule itself will just determine the order to play them (with the option to play the same program multiple times). This will help compress the json but it will also allow things like letting time slots exist without removing programs not in the time slots. But that's something for 1.3 or 1.4 I think. 1.2 needs to be a lot more stable before moving on to those things.

**Comment by vexorian** [comment]
This will be possible in 1.5.0
