### ISSUE TITLE
Backend Programming modal "hidden" update button on some screen res

### ISSUE THREAD

**Issue by scoobshub** [vexorian/dizquetv#182]
**VERSION:** 1.2.1

Just saw this on a MacBook Pro 15" (1440x900px): when in backend -> channel editing modal -> programming tab, it's impossible to save because the button is not show (even if you scroll at the very bottom, you still have to either zoom out or go in another tab and press "Update Channel").

Attaching a [screenshot](https://ucddb414752c3a9492d65a564d54.previews.dropboxusercontent.com/p/thumb/AA81_PuPk5XDofNTVJ9y0CNv0Hf50hHDQlavhhOQ-a7-RRM7R5VmRjq-JpijbSyVfYi2b6WHt1DRMSoHOmKZp9iVNzIB_O7VX2FUSwkhE_SOf2J3cR7OaiLi8FM2YXRb2qjYKyvG1REWfz3Is590I1AAzSjp4MQGDd5Fxb8gh6WtN5dGAjG1Zi3D30uFKNq-HPEJ71obElTtYBKJSASKjQIluyliVj44Rj97kogXuuHm0NgRz0ZazNBe5amoKQA7Yq0IpSvfMLmWum3LOVkmq67Q4bW9BmEa5GTnMN3mnGvShHCn_MamCGj4U9Ie8LZ3v07JlFzzxzaSti4a9IH-yOlSzFBHPfbAgtm2MjwL8VKaYL2fYAMCeYff2_ZEe-3iIUpPL8CcmpooS1rKA_pH0VY1/p.png?size=2048x1536&size_mode=3) to better understand this.

**Comment by vexorian** [comment]
Yeah this is pretty much a bug, with any short height browser window.

**Comment by vexorian** [comment]
This is not going to be fixed in the next version per-se. It's very difficult to control the virtual scrolling and the modal dialog and the tools side bar all at once. So the only way was to have a fixed height for the programming list. Fixed means not dynamic. So I can't do something like "If screen is short, use a short height". 

For the time being, the only work-around possible was to add buttons that will allow to make the list shorter in case you can't really access the buttons. You can also make it larger if your resolution is really tall.

For 1.3.x, the plan is to rework the whole "programming" entirely, so I will have to rethink, once again, how the tool buttons will work and we can fix this issue in some cleaner manner.
