### ISSUE TITLE
Time slots + Flex time timing errors

### ISSUE THREAD

**Issue by scoobshub** [vexorian/dizquetv#184]
When using time slots (like in a movie channel) to have a movie always start at 9:00PM -as suggested by Vexorian on Discord- we add a Flex at 08:30PM. That works except for the fact that Flex(es) are added with (?) no apparent logic and they tend to also get very huge.

Here you can see some screenshots: the channel setup is [this](https://www.dropbox.com/s/84rpgvyrziaby0c/Schermata%202020-11-03%20alle%2021.24.30.png?dl=0), flexes are automatically added [this](https://www.dropbox.com/s/3hboaybr8lcu946/Schermata%202020-11-03%20alle%2021.19.47.png?dl=0) way but i can't see a logic: 
- Shouldn't flex time be more equally distributed during the day to have lots of small-medium flex and avoid huge ones? 
- In some days you can have Flex even 1-2 hours long, shouldn't Dizquetv pick a movie instead?
- Shouldn't Flexes be always present? (In the screenshot you can see sometimes they're not, and that's always happening with that same movie)

Thanks

**Comment by vexorian** [comment]
Thanks, I knew htis is an issue, but I was unable to reproduce. Hopefully your screenshot will help.

> Shouldn't Flexes be always present?

dizqueTV's algorithms frequently consider a delay of a couple or seconds to not be a big deal. So for example if you want something to start at 4:00:00 , but due to small size discrepancies, it starts at 3:59:58 , it will pretend it's not a big deal.

**Comment by MoRBiD-MaNGLeR** [comment]
I had Time Slots add a large amount of Flex time.  I worked around the issue by adding multiple movie Time Slots to split up the Flex Time to be between the movie Time Slots, rather than grouped at the end of the overall movies Time Slot.  However, this required that I schedule the Time Slots close to my actual movie durations.

**Comment by vexorian** [comment]
On second inspection the flex times are not that long. I was thinking of an actual bug in which it adds a month's long flex time.

Regarding this specific case, adding 2 hours of flex near the end of a block.

> Shouldn't flex time be more equally distributed during the day to have lots of small-medium flex and avoid huge ones?

I am not sure. When someone comes and tells me, "I want to play movies at 21:00", then that sounds like a contract, and it will try to fill up the 24 hours until the next 21:00 slot. Since movies are huge entities, what often happens is that a movie will end at 19:00 and the next movie just happens to be longer than 2 hours.

* I could try to distribute the remaining 2 hours of flex time and make the flex times inside the slot larger. The problem is that  in some cases this means spreading the problem. Could reach a situation in which you have 3 gaps of 30 minutes instead of a single cap of 90 minutes at the end. It's subjective which one is preferred. Could be made an option.

* I could play the next movie anyway, but this will cause the starting time to slide from 21:00 to something else. The "lateness" setting allows to setup some slack in this. But if it slides too much, then we are no longer really following the "Play a movie at 21:00" contract, which is the whole point of time slots.

* I could play a different , shorter movie instead of the next one. This adds other issues, first of all, the only movie small enough to play might be so small that there's still a huge flex portion after that movie, so we accomplish nothing. The other issue is that this will add a bias towards short movies, making them more likely to play in average.

**Comment by scoobshub** [comment]
Hi @vexorian I think that the point here is to understand the whole direction of the Time Slot feature and of DizqueTV in general. If it's gonna be as close as possible to a real tv channel, i think that respecting timing (and programmaming) is essential (if I wanna watch a movie channel, i expect to just see movies...not 2-3 hours long flex).

I can't understand why movies added to a channel and flex can't be handled in a way that would avoid to create huge "gaps" between content. If i "fix" a movie at 9:00 "per contract", then DizqueTV should pick movies from the ones added to the channel to fill the remaining times. If there's some time left shorter than any of the movies added to the channel, DizqueTV should then create equally distributed flexes during the day.

Thanks

**Comment by vexorian** [comment]
For example, if you just want a channel fulll of movies without gaps, you can do it by adding all the movies to the channel then using ther "Replicate and shuffle" function. 

Time Slots is for people who want to have control over the starting times of shows/movies. Like if you want a channel that plays The Simpsons at 19:30 and a movie at 20:00 and you want that to be the case all the time.

The problem is that movies and even episodes of the same show have varying lengths.  So if that Simpsons episode isn't exactly 30 minutes-long, you can't really have a movie start at 20:00 without adding a gap.

> f i "fix" a movie at 9:00 "per contract", then DizqueTV should pick movies from the ones added to the channel to fill the remaining times.

When programming I cannot really make assumptions about the sort of movies that you will pick for the channel. So for what all I know they may have any length from 45 minutes-long to 3 hours. I also don't have control over the length of the blocks that they will pick. Some users might pick 24 hours blocks. Other users 5 hours.

Right now what it does is generate a fixed, random order for the movies to play.  This is because otherwise we would start having trouble with some movies being picked too frequently. If you add 40 movies to a channel, you don't want Avengers to play 5 times in a row in the same week.

I could on the other hand try to accomodate the movies neatly in every block to minimize the number of gaps. In fact, this is how Flex time works. But the problem is that some combinations of movies will fit the block much better than others. Like if you have a 5 hours movie block, and two of your movies happen to be exactly 2.4 hours long. Then this sort of algorithm will love to pick those two movies. Al of the time. I would stop getting less feedback about long gaps, but I would start receiving more feedback about too many repetitions in the randomization.
