### ISSUE TITLE
Time Slot - allow more times

### ISSUE THREAD

**Issue by scoobshub** [vexorian/dizquetv#207]
Currently the "Time" field in time slot is limited to 00, 15, 30, 45 options. It could be useful to have more granular timing options like 00, 05, 10, 15, .., 55. 
Even better, if doable,  instead of a selection this field could be changed in some kind of input leaving an even finer choice to the user (thinking about to the minute options) 🤔

**Comment by vexorian** [comment]
Right now there's a problem with the ui to pick the hour. I could add more time options, but it is already too hard to pick the exact hour you want because of all the scrolling. If I add mod 5 and mod 10, the scrolling will triple. So I think the only solution is to get a better widget for picking the time of day. I just didn't have enough time to find a good one when developing 1.2.

**Comment by vexorian** [comment]
So in 1.3.0 there's a better time picker.
