### ISSUE TITLE
Custom Show Name Not In Guide??

### ISSUE THREAD

**Issue by GlobalServer500** [vexorian/dizquetv#301]
I noticed the custom show name I assigned for both "Looney Tunes" and "Three Stooges" is listed in the guide as the episode names and not as  2 hour "looney tunes" or "three stooges" show? Did I do something wrong? Because those clips are short, I want them as a TV show that lasts 2 hours instead of all the small clips in the guide.

Also, I noticed if I pad times in my time slot, and then add "Looney Tunes" custom TV show for 2 hours, the episodes will only play one clip per half hour. Can I still pad times to 00, and 30 but have the custom tv show not follow that rule so one small clip plays after the other for my desired time range on my custom tv show, but the padding on my main schedule still remains?

**Comment by vexorian** [comment]
There's a feature incoming that will be "custom episodes", which will allow you to make sure different videos play in bulk as if they were a single episode, and possibly choices as to how it will look in the TV guide. I think that's what you want.

Custom Shows are more for letting you to organize multiple videos as if they were the same show. TV Guide ignores it though. That's by design. When Custom Episodes are made, the TV guide aspect will be possible.

**Comment by GlobalServer500** [comment]
Thanks for answering my question. Yes, that was what I was thinking of.  I will just wait for that feature then when it becomes available, it's not a big deal. I'll close this topic then since my question was answered.
