### ISSUE TITLE
XML File Location Unraid

### ISSUE THREAD

**Issue by magaman** [vexorian/dizquetv#4]
Installed the Unraid docker fine, able to detect the tuner but can't get past the xml location step. Tried a bunch of different paths and can't seem to get the right one. I didn't alter any settings installing the docker, any idea?

**Comment by vexorian** [comment]
The unraid docker supposedly creates a volume that points to .dizquetv folder. The xmltv should appear in the host's folder that's used by this volume

**Comment by magaman** [comment]
Yeah I see the file and directory created, but I think since I'm inputting it into Plex's UI the path is being based off the volume Plex uses

**Comment by vexorian** [comment]
So plex is also in a container, huh?

I suggest using the address instead of a path location. In the dizqueTV Web ui, there's a XMLTV icon at the top-right of the screen, this one holds the web address to the xmltv file. Use that address in plex.

Otherwise, you'd need to have a shared volume between plex and dizqueTV, probably too much problem

**Comment by magaman** [comment]
AHHHH, BINGO using the full URL worked.
