### ISSUE TITLE
Custom Resolutions

### ISSUE THREAD

**Issue by Toddimyre** [vexorian/dizquetv#47]
Would it be possible to add custom resolutions to the ffmpeg encoder? I'm currently looking to target 480 x 270. That might sound ridiculous, but I managed to get your software running on a Raspberry Pi 4 with Ubuntu Server 20.04, and it doesn't offer smooth playback on the higher resolutions.

**Comment by Toddimyre** [comment]
Update: I have discovered that you can manually adjust the resolution in the json file and it appears to work just fine.

**Comment by MoRBiD-MaNGLeR** [comment]
@Toddimyre Safe to assume editing the JSON file is an adequate workaround until this enhancement request can be explored?

I would have recommended we close it since you have a workaround, but I see long-term value in supporting other Raspberry Pi 4 users with this solution, and in general, keeping users out of the JSON files.

**Comment by vexorian** [comment]
@Toddimyre Well, to be honest when I was adding the preset resolutions, I was wondering what kind of resolutions people would want to use in low-res settings. I tried to go to wikipedia for the most used ones, and thought that should a custom one be necessary, they can always edit the json. 

480x270 sounds like a cool preset to add because it is 16:9 but still small. I will add it, but yeah I think that in general for other resolutions people should edit the json. Adding a better UI that has customization for this would be the best like an (add resolution) thing, but implementing it sounds like too much effort when the app has so many issues in other areas. So for now I will add 480x270 as an option for low resource devices. Great news that it runs at all on a PI 4. I guess you ran it from source?

**Comment by MoRBiD-MaNGLeR** [comment]
@vexorian Sound about right?

Enhancement Request:  480x270 will be added as an option for low-resource devices.
Won't Fix:  Won't add other custom resolutions for ffmpeg encoding.  Want custom?  Edit JSON.

**Comment by Toddimyre** [comment]
Sorry for the delay. I just woke up. Lol.

@MoRBiD-MaNGLeR Yes. When I edited the json file, the resolution worked properly. It doesn't show up in the GUI, but it's all good. There's a blank space where the resolution would normally go.

@vexorian Yes. I ran your build from source and grabbed the other needed files from the Ubuntu repo. To set it up, you have to build it like your docker instructions. You need ffmpeg, nodejs, and npm installed from the repo to make it work properly on case you're wondering. It does have a slight delay as the encoder speeds up, but ran pretty smooth after it was going.

**Comment by MoRBiD-MaNGLeR** [comment]
@Toddimyre, I believe @vexorian already coded the 480x270 option for inclusion in an upcoming build.

After you two are done having your conversation, @vexorian, could you please close?  Thanks.

**Comment by vexorian** [comment]
I just wanted to know if they compiled from source. Closing
