### ISSUE TITLE
Trying to play media causes PMS to crash

### ISSUE THREAD

**Issue by steampunk85** [vexorian/dizquetv#7]
PMS Version 1.19.5.3112
Windows 10 Pro V. 1909 64-bit
Processor: i5-7400 3.00GHz
RAM: 16GB

Ive created 16 channels in the web gui and added shows to all. When I go to the guide and attempt to play something, it keeps circling and after about 10 seconds, Plex Media Server Service crashes on my server. I have not been able to start a file as of yet. ffmpeg is installed with newest build.

**Comment by vexorian** [comment]
First, we need to isolate if it is a Plex issue or a dizque issue.  (Well, it is in part a Plex bug , because DVR data shouldn't be able to crash it)

You can run your channels in VLC without Plex

For example, to play channel 1:

I play "http://192.168.0.10:8000/video?channel=1" in VLC.

If that also crashes, the next thing to see is to run the channel in VLC while you are seeing dizque's TV logs and see what happens there.

**Comment by steampunk85** [comment]
it plays on VLC but with no audio

**Comment by steampunk85** [comment]
seems it was due to plex settings. the hardware transcoding was turned on by accident and since i have no hardware to transcode with, it was causing it to fail.
