### ISSUE TITLE
Show Flex Time on Episode Guide

### ISSUE THREAD

**Issue by rfinley** [vexorian/dizquetv#86]
I've been setting up flex time so shows start at fixed times. In the episode guide, it shows as a stretched show. This is particularly bad when I click into the end of a show and get an error because there's really nothing to play. It would be far more valuable (to me) to show the breaks as breaks or as just blank space.

**Comment by kwbisch** [comment]
Probably should be an option.  I would prefer it the way that it is currently.

**Comment by rfinley** [comment]
On reddit you asked this be opened as an issue on GitHub.  Does this mean you intend to create this as an option, with the default of course being the way you prefer?

**Comment by kwbisch** [comment]
Sorry, OP, I'm not the developer... just making a comment as another user.

**Comment by vexorian** [comment]
In the first iteration of Flex time, it showed as empty space in the TV guide. Unfortunately, it turns out that empty space causes issues in many clients. Like you are not able to play the channel at all in some Plex channels and a similar issue in Kodi.

If I add the flex time it shows up as a movie in the guide so that's also sub-optimal.

So the logic right now is that if the flex time is shorter than 30 minutes, it is melded with the previous program. If it is longer than 30 minutes, it shows up in the TV guide as the channel's name. I would actually prefer the thing with the empty space, but clients just break too much with it.

**Comment by rfinley** [comment]
That makes good sense.  Thank you for considering the enhancement request.

**Comment by vexorian** [comment]
As much as I would prefer this to be the way it worked, it causes too many issues with clients so I am tagging it won't fix and closing it.
