### ISSUE TITLE
Not All Programs Showing Up When Adding

### ISSUE THREAD

**Issue by kenstone** [vexorian/dizquetv#88]
I've got an issue where, when I attempt to add a series folder, only 1 of the folders is getting pulled in. There's 9 seasons, but only season 2 is showing up. I can view any of the seasons in Plex.  Other series, none of the episodes pull in. But, in yet other cases, the full series will get pulled in. On .65

**Comment by kenstone** [comment]
Interesting. This was a new Plex server install. It's now about a day or so later, and the same series now imports all of the episodes.

**Comment by MoRBiD-MaNGLeR** [comment]
@kenstone Perhaps Plex finished importing all of your shows and loading all of its metadata?  Should we close out the reported issue?

**Comment by kenstone** [comment]
Yeah I think that's fine. I just thought it strange because I could see them all in Plex, so I figured it was all in there.

**Comment by timmehtimtims** [comment]
I'm having this same issue. I only setup Dizquetv last night on a plex library that has been around a while (all metadata present). I added shows to the channel last night, but it only added 1 episode of a 9 season show. I've come back to it the next day and the issue is still occurring.
Nothing in the logs I'm afraid.
Could this be a permissions issue?
