### ISSUE TITLE
Channel at Night repeating after program content ends on main channel

### ISSUE THREAD

**Issue by kwbisch** [vexorian/dizquetv#96]
I may have found a bug in .67.  I am trying to set up a new channel with Channel at Night.  I add one TV show that has 4 seasons with roughly 80 episodes, totaling 22 1/2 hours of content.  I then try to add "Channel at Night" to run from 18:00 - 22:00.  It adds that (it actually starts a few minutes early, at 17:52, presumably the end of the prior program?) and runs until 22:00.  It switches back to my original programming until it runs the final episode of original programming and then it goes back to redirect until 10:00 pm the next day. 

In other words, my original content ran out and rather than the daytime programming starting from the beginning, the channel switched to "Channel at Night" programming even though it was not time for it to start.

_This is slightly different than I explained on Discord, I couldn't exactly duplicate it, but this is the same behavior._

![issue2-1](https://user-images.githubusercontent.com/42160517/92339442-bd8d0200-f07b-11ea-937a-cf2ebe233742.png)

![issue2-2](https://user-images.githubusercontent.com/42160517/92339450-c54ca680-f07b-11ea-9561-4dcb98b22ab3.png)

**Comment by vexorian** [comment]
It's a bug. The empty space outside the night hours should be replaced with Flex time in a correct implementation. But note that there would still be a lot of flex time in the second day because there isn't a lot of programming. My suggestion would be to duplicate or triplicate the episodes to avoid the issue.

**Comment by kwbisch** [comment]
Why wouldn't the programming start over like in channels that don't have the night hours?

**Comment by vexorian** [comment]
The programming starts over. But the night hours are part of the programming.  So i would have to generate the repetition as part of the programming for it work correctly. But this has the risk of possibly adding a lot of copies of the shows automatically and possibly messing up with the balance. Hence I prefer it to be done manually.

I think I will add a button to add repetitions of the channel so that you can play with it before clicking channel at night.

If you test with restrict hours, try restrict hours in this channel, banning the time from 18:00 to 22:00. There will be a huge Flex gap in the second day.
